//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrunkenBakery.OWAtray.GUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OWAtray {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OWAtray() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrunkenBakery.OWAtray.GUI.OWAtray", typeof(OWAtray).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About OWA Tray Monitor.
        /// </summary>
        internal static string About_OWA_Tray_Monitor {
            get {
                return ResourceManager.GetString("About_OWA_Tray_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        internal static string Advanced_Settings {
            get {
                return ResourceManager.GetString("Advanced_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always open OWA in IE.
        /// </summary>
        internal static string Always_open_OWA_in_IE {
            get {
                return ResourceManager.GetString("Always_open_OWA_in_IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always use IE switched.
        /// </summary>
        internal static string Always_use_IE_switched {
            get {
                return ResourceManager.GetString("Always_use_IE_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to use Autodiscovery.
        /// </summary>
        internal static string Attempt_to_use_Autodiscovery {
            get {
                return ResourceManager.GetString("Attempt_to_use_Autodiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audible notifications switched.
        /// </summary>
        internal static string Audible_notifications_switched {
            get {
                return ResourceManager.GetString("Audible_notifications_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodetect.
        /// </summary>
        internal static string Autodetect {
            get {
                return ResourceManager.GetString("Autodetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered EWS Url:.
        /// </summary>
        internal static string Autodiscovered_EWS_Url {
            get {
                return ResourceManager.GetString("Autodiscovered_EWS_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered Mailbox Server:.
        /// </summary>
        internal static string Autodiscovered_Mailbox_Server {
            get {
                return ResourceManager.GetString("Autodiscovered_Mailbox_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered OWA Url:.
        /// </summary>
        internal static string Autodiscovered_OWA_Url {
            get {
                return ResourceManager.GetString("Autodiscovered_OWA_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered User Name:.
        /// </summary>
        internal static string Autodiscovered_User_Name {
            get {
                return ResourceManager.GetString("Autodiscovered_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodiscovery is switched.
        /// </summary>
        internal static string Autodiscovery_is_switched {
            get {
                return ResourceManager.GetString("Autodiscovery_is_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodiscovery requires an Email address to be specified. Please check settings..
        /// </summary>
        internal static string Autodiscovery_requires_an_Email {
            get {
                return ResourceManager.GetString("Autodiscovery_requires_an_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodiscovery Validation override switched.
        /// </summary>
        internal static string Autodiscovery_Validation {
            get {
                return ResourceManager.GetString("Autodiscovery_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Login is switched.
        /// </summary>
        internal static string Automatic_Login_is_switched {
            get {
                return ResourceManager.GetString("Automatic_Login_is_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autostart with Windows.
        /// </summary>
        internal static string autostart_with_Windows {
            get {
                return ResourceManager.GetString("autostart_with_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balloon.
        /// </summary>
        internal static string Balloon {
            get {
                return ResourceManager.GetString("Balloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balloon notifications switched.
        /// </summary>
        internal static string Balloon_notifications_switched {
            get {
                return ResourceManager.GetString("Balloon_notifications_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Settings.
        /// </summary>
        internal static string Basic_Settings {
            get {
                return ResourceManager.GetString("Basic_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding to Exchange....
        /// </summary>
        internal static string Binding_to_Exchange {
            get {
                return ResourceManager.GetString("Binding_to_Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bit).
        /// </summary>
        internal static string bit {
            get {
                return ResourceManager.GetString("bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar notifications switched.
        /// </summary>
        internal static string Calendar_notifications_switched {
            get {
                return ResourceManager.GetString("Calendar_notifications_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t establish a valid URL for Exchange. Please check settings..
        /// </summary>
        internal static string Can_establish_valid_URL_for {
            get {
                return ResourceManager.GetString("Can_establish_valid_URL_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan.
        /// </summary>
        internal static string Catalan {
            get {
                return ResourceManager.GetString("Catalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log.
        /// </summary>
        internal static string Change_Log {
            get {
                return ResourceManager.GetString("Change_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiled on .NET.
        /// </summary>
        internal static string Compiled_on_NET {
            get {
                return ResourceManager.GetString("Compiled_on_NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to.
        /// </summary>
        internal static string Connected_to {
            get {
                return ResourceManager.GetString("Connected_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        internal static string Contact_Details {
            get {
                return ResourceManager.GetString("Contact_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Date stamping switched off.
        /// </summary>
        internal static string Date_stamping_switched_off {
            get {
                return ResourceManager.GetString("Date_stamping_switched_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Date stamping switched on.
        /// </summary>
        internal static string Date_stamping_switched_on {
            get {
                return ResourceManager.GetString("Date_stamping_switched_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days or.
        /// </summary>
        internal static string days_or {
            get {
                return ResourceManager.GetString("days_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent Assemblies:.
        /// </summary>
        internal static string Dependent_Assemblies {
            get {
                return ResourceManager.GetString("Dependent_Assemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected System Settings.
        /// </summary>
        internal static string Detected_System_Settings {
            get {
                return ResourceManager.GetString("Detected_System_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Calendar.
        /// </summary>
        internal static string Disable_Calendar {
            get {
                return ResourceManager.GetString("Disable_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address :.
        /// </summary>
        internal static string Email_Address {
            get {
                return ResourceManager.GetString("Email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint is INSIDE corporate network.
        /// </summary>
        internal static string Endpoint_is_INSIDE_corporate {
            get {
                return ResourceManager.GetString("Endpoint_is_INSIDE_corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint is OUTSIDE corporate network.
        /// </summary>
        internal static string Endpoint_is_OUTSIDE_corporate {
            get {
                return ResourceManager.GetString("Endpoint_is_OUTSIDE_corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when getting email properties:.
        /// </summary>
        internal static string Error_when_getting_email {
            get {
                return ResourceManager.GetString("Error_when_getting_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Details.
        /// </summary>
        internal static string Event_Details {
            get {
                return ResourceManager.GetString("Event_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EWS URL override switched.
        /// </summary>
        internal static string EWS_URL_override_switched {
            get {
                return ResourceManager.GetString("EWS_URL_override_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Version.
        /// </summary>
        internal static string Exchange_Version {
            get {
                return ResourceManager.GetString("Exchange_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  freshly baked at .
        /// </summary>
        internal static string Form1_WindowDressing__freshly_baked_at_ {
            get {
                return ResourceManager.GetString("Form1_WindowDressing__freshly_baked_at_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering data, please wait....
        /// </summary>
        internal static string Gathering_data_please_wait {
            get {
                return ResourceManager.GetString("Gathering_data_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gb (.
        /// </summary>
        internal static string Gb {
            get {
                return ResourceManager.GetString("Gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gb free).
        /// </summary>
        internal static string Gb_free {
            get {
                return ResourceManager.GetString("Gb_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl.
        /// </summary>
        internal static string Growl {
            get {
                return ResourceManager.GetString("Growl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl notifications switched.
        /// </summary>
        internal static string Growl_notifications_switched {
            get {
                return ResourceManager.GetString("Growl_notifications_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in your inbox.
        /// </summary>
        internal static string in_your_inbox {
            get {
                return ResourceManager.GetString("in_your_inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed MDAC Versions.
        /// </summary>
        internal static string Installed_MDAC_Versions {
            get {
                return ResourceManager.GetString("Installed_MDAC_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed .NET Versions.
        /// </summary>
        internal static string Installed_NET_Versions {
            get {
                return ResourceManager.GetString("Installed_NET_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file is.
        /// </summary>
        internal static string Log_file_is {
            get {
                return ResourceManager.GetString("Log_file_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Log files are NOT size limited.
        /// </summary>
        internal static string Log_files_are_NOT_size {
            get {
                return ResourceManager.GetString("Log_files_are_NOT_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Log files are size limited (currently.
        /// </summary>
        internal static string Log_files_are_size_limited {
            get {
                return ResourceManager.GetString("Log_files_are_size_limited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Log files will be scavenged (after.
        /// </summary>
        internal static string Log_files_will_be_scavenged {
            get {
                return ResourceManager.GetString("Log_files_will_be_scavenged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Log files will NOT be scavenged.
        /// </summary>
        internal static string Log_files_will_NOT_be {
            get {
                return ResourceManager.GetString("Log_files_will_NOT_be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging error 1:.
        /// </summary>
        internal static string Logging_error {
            get {
                return ResourceManager.GetString("Logging_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging error 2:.
        /// </summary>
        internal static string Logging_error1 {
            get {
                return ResourceManager.GetString("Logging_error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Logging Started.
        /// </summary>
        internal static string Logging_Started {
            get {
                return ResourceManager.GetString("Logging_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Logging Stopped.
        /// </summary>
        internal static string Logging_Stopped {
            get {
                return ResourceManager.GetString("Logging_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Automatically.
        /// </summary>
        internal static string Login_Automatically {
            get {
                return ResourceManager.GetString("Login_Automatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail functions will now be handled by OWA.
        /// </summary>
        internal static string Mail_functions_will_now_be {
            get {
                return ResourceManager.GetString("Mail_functions_will_now_be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail handler restored to system default.
        /// </summary>
        internal static string Mail_handler_restored_to_system {
            get {
                return ResourceManager.GetString("Mail_handler_restored_to_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Version.
        /// </summary>
        internal static string Major_Version {
            get {
                return ResourceManager.GetString("Major_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make OWA Default.
        /// </summary>
        internal static string Make_OWA_Default {
            get {
                return ResourceManager.GetString("Make_OWA_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mb).
        /// </summary>
        internal static string Mb {
            get {
                return ResourceManager.GetString("Mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mb total size).
        /// </summary>
        internal static string Mb_total_size {
            get {
                return ResourceManager.GetString("Mb_total_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDAC Inspector.
        /// </summary>
        internal static string MDAC_Inspector {
            get {
                return ResourceManager.GetString("MDAC_Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDAC Versions.
        /// </summary>
        internal static string MDAC_Versions {
            get {
                return ResourceManager.GetString("MDAC_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        internal static string mins {
            get {
                return ResourceManager.GetString("mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a numeric value between 1 and.
        /// </summary>
        internal static string Must_be_numeric_value_between {
            get {
                return ResourceManager.GetString("Must_be_numeric_value_between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Inspector.
        /// </summary>
        internal static string NET_Inspector {
            get {
                return ResourceManager.GetString("NET_Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Versions.
        /// </summary>
        internal static string NET_Versions {
            get {
                return ResourceManager.GetString("NET_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mail.
        /// </summary>
        internal static string New_Mail {
            get {
                return ResourceManager.GetString("New_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mail from.
        /// </summary>
        internal static string New_Mail_from {
            get {
                return ResourceManager.GetString("New_Mail_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No Location&gt;.
        /// </summary>
        internal static string No_Location {
            get {
                return ResourceManager.GetString("No_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No Sender&gt;.
        /// </summary>
        internal static string No_Sender {
            get {
                return ResourceManager.GetString("No_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No Subject&gt;.
        /// </summary>
        internal static string No_Subject {
            get {
                return ResourceManager.GetString("No_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No Title&gt;.
        /// </summary>
        internal static string No_Title {
            get {
                return ResourceManager.GetString("No_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not.
        /// </summary>
        internal static string not {
            get {
                return ResourceManager.GetString("not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected to Exchange.
        /// </summary>
        internal static string Not_Connected_to_Exchange {
            get {
                return ResourceManager.GetString("Not_Connected_to_Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office365 login override.
        /// </summary>
        internal static string Office_login_override {
            get {
                return ResourceManager.GetString("Office_login_override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Outlook.
        /// </summary>
        internal static string Open_Outlook {
            get {
                return ResourceManager.GetString("Open_Outlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open OWA.
        /// </summary>
        internal static string Open_OWA {
            get {
                return ResourceManager.GetString("Open_OWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        internal static string Operating_System {
            get {
                return ResourceManager.GetString("Operating_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other new emails.
        /// </summary>
        internal static string other_new_emails {
            get {
                return ResourceManager.GetString("other_new_emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to others.
        /// </summary>
        internal static string others {
            get {
                return ResourceManager.GetString("others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Autodiscovery Validation.
        /// </summary>
        internal static string Override_Autodiscovery {
            get {
                return ResourceManager.GetString("Override_Autodiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Certificate.
        /// </summary>
        internal static string Override_Certificate {
            get {
                return ResourceManager.GetString("Override_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWA URL override switched.
        /// </summary>
        internal static string OWA_URL_override_switched {
            get {
                return ResourceManager.GetString("OWA_URL_override_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWAtray will.
        /// </summary>
        internal static string OWAtray_will {
            get {
                return ResourceManager.GetString("OWAtray_will", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Sound.
        /// </summary>
        internal static string Play_Sound {
            get {
                return ResourceManager.GetString("Play_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a valid email address or username..
        /// </summary>
        internal static string Please_supply_valid_email {
            get {
                return ResourceManager.GetString("Please_supply_valid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a valid password..
        /// </summary>
        internal static string Please_supply_valid_password {
            get {
                return ResourceManager.GetString("Please_supply_valid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall Last Popup.
        /// </summary>
        internal static string Recall_Last_Popup {
            get {
                return ResourceManager.GetString("Recall_Last_Popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Tray Icon.
        /// </summary>
        internal static string Reset_Tray_Icon {
            get {
                return ResourceManager.GetString("Reset_Tray_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring Mail handlers.
        /// </summary>
        internal static string Restoring_Mail_handlers {
            get {
                return ResourceManager.GetString("Restoring_Mail_handlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        internal static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at Startup.
        /// </summary>
        internal static string Run_at_Startup {
            get {
                return ResourceManager.GetString("Run_at_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running on .NET v.
        /// </summary>
        internal static string Running_on_NET {
            get {
                return ResourceManager.GetString("Running_on_NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second timer started.
        /// </summary>
        internal static string second_timer_started {
            get {
                return ResourceManager.GetString("second_timer_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address :.
        /// </summary>
        internal static string Server_Address {
            get {
                return ResourceManager.GetString("Server_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up Mail handlers.
        /// </summary>
        internal static string Setting_up_Mail_handlers {
            get {
                return ResourceManager.GetString("Setting_up_Mail_handlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Integration.
        /// </summary>
        internal static string Shell_Integration {
            get {
                return ResourceManager.GetString("Shell_Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snarl.
        /// </summary>
        internal static string Snarl {
            get {
                return ResourceManager.GetString("Snarl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snarl notifications switched.
        /// </summary>
        internal static string Snarl_notifications_switched {
            get {
                return ResourceManager.GetString("Snarl_notifications_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL Certificate override switched.
        /// </summary>
        internal static string SSL_Certificate_override {
            get {
                return ResourceManager.GetString("SSL_Certificate_override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Autodiscovery.
        /// </summary>
        internal static string Starting_Autodiscovery {
            get {
                return ResourceManager.GetString("Starting_Autodiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Information.
        /// </summary>
        internal static string Support_Information {
            get {
                return ResourceManager.GetString("Support_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Off.
        /// </summary>
        internal static string Switch_Off {
            get {
                return ResourceManager.GetString("Switch_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        internal static string System_Information {
            get {
                return ResourceManager.GetString("System_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminating.
        /// </summary>
        internal static string Terminating {
            get {
                return ResourceManager.GetString("Terminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are.
        /// </summary>
        internal static string There_are {
            get {
                return ResourceManager.GetString("There_are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer stopped.
        /// </summary>
        internal static string Timer_stopped {
            get {
                return ResourceManager.GetString("Timer_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many appointments!.
        /// </summary>
        internal static string Too_many_appointments {
            get {
                return ResourceManager.GetString("Too_many_appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too much mail!.
        /// </summary>
        internal static string Too_much_mail {
            get {
                return ResourceManager.GetString("Too_much_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        internal static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unread email.
        /// </summary>
        internal static string unread_email {
            get {
                return ResourceManager.GetString("unread_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Interval :.
        /// </summary>
        internal static string Update_Interval {
            get {
                return ResourceManager.GetString("Update_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Domain Credentials.
        /// </summary>
        internal static string Use_Windows_Domain_Credentials {
            get {
                return ResourceManager.GetString("Use_Windows_Domain_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User :.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the.
        /// </summary>
        internal static string Welcome_to_the {
            get {
                return ResourceManager.GetString("Welcome_to_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Domain :.
        /// </summary>
        internal static string Windows_Domain {
            get {
                return ResourceManager.GetString("Windows_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not an Admin user. Operation may fail..
        /// </summary>
        internal static string You_are_not_an_Admin_user {
            get {
                return ResourceManager.GetString("You_are_not_an_Admin_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        internal static string You_have {
            get {
                return ResourceManager.GetString("You_have", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an appointment in.
        /// </summary>
        internal static string You_have_an_appointment_in {
            get {
                return ResourceManager.GetString("You_have_an_appointment_in", resourceCulture);
            }
        }
    }
}
