//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrunkenBakery.OWAtray.Connections.EWS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrunkenBakery.OWAtray.Connections.EWS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed state to.
        /// </summary>
        internal static string EwsConnection_ChangeState_Changed_state_to {
            get {
                return ResourceManager.GetString("EwsConnection_ChangeState_Changed_state_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subject.
        /// </summary>
        internal static string EwsConnection_CheckForNewMail_No_subject {
            get {
                return ResourceManager.GetString("EwsConnection_CheckForNewMail_No_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a Password.
        /// </summary>
        internal static string EwsConnection_Connect_Please_provide_a_Password {
            get {
                return ResourceManager.GetString("EwsConnection_Connect_Please_provide_a_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid Email Address.
        /// </summary>
        internal static string EwsConnection_Connect_Please_provide_a_valid_Email_Address {
            get {
                return ResourceManager.GetString("EwsConnection_Connect_Please_provide_a_valid_Email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid Server Address.
        /// </summary>
        internal static string EwsConnection_Connect_Please_provide_a_valid_Server_Address {
            get {
                return ResourceManager.GetString("EwsConnection_Connect_Please_provide_a_valid_Server_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWAtray Test Message.
        /// </summary>
        internal static string EwsConnection_Send_OWAtray_Test_Message {
            get {
                return ResourceManager.GetString("EwsConnection_Send_OWAtray_Test_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send. Email provider is disconnected..
        /// </summary>
        internal static string EwsConnection_Send_Unable_to_send__Email_provider_is_disconnected_ {
            get {
                return ResourceManager.GetString("EwsConnection_Send_Unable_to_send__Email_provider_is_disconnected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send. No recipient specified..
        /// </summary>
        internal static string EwsConnection_Send_Unable_to_send__No_recipient_specified_ {
            get {
                return ResourceManager.GetString("EwsConnection_Send_Unable_to_send__No_recipient_specified_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string EwsConnection_Version_Default {
            get {
                return ResourceManager.GetString("EwsConnection_Version_Default", resourceCulture);
            }
        }
    }
}
