//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrunkenBakery.OWAtray.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrunkenBakery.OWAtray.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BlankLine {
            get {
                return ResourceManager.GetString("BlankLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create log file.
        /// </summary>
        internal static string CreateLogFail {
            get {
                return ResourceManager.GetString("CreateLogFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------------------------------------------------------------.
        /// </summary>
        internal static string Dashes {
            get {
                return ResourceManager.GetString("Dashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Date stamping switched off.
        /// </summary>
        internal static string DateOff {
            get {
                return ResourceManager.GetString("DateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Date stamping switched on.
        /// </summary>
        internal static string DateOn {
            get {
                return ResourceManager.GetString("DateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days or.
        /// </summary>
        internal static string DaysOr {
            get {
                return ResourceManager.GetString("DaysOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete log file.
        /// </summary>
        internal static string DeleteLogFail {
            get {
                return ResourceManager.GetString("DeleteLogFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file is.
        /// </summary>
        internal static string LogFile {
            get {
                return ResourceManager.GetString("LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write log entry, logging disabled.
        /// </summary>
        internal static string LoggingDisabled {
            get {
                return ResourceManager.GetString("LoggingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Logging Started.
        /// </summary>
        internal static string LoggingStarted {
            get {
                return ResourceManager.GetString("LoggingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Logging Stopped.
        /// </summary>
        internal static string LoggingStopped {
            get {
                return ResourceManager.GetString("LoggingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mb).
        /// </summary>
        internal static string Mb {
            get {
                return ResourceManager.GetString("Mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mb total size).
        /// </summary>
        internal static string MbTotal {
            get {
                return ResourceManager.GetString("MbTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log does not exist!.
        /// </summary>
        internal static string NoEventLog {
            get {
                return ResourceManager.GetString("NoEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Log files will NOT be scavenged.
        /// </summary>
        internal static string NoScavenge {
            get {
                return ResourceManager.GetString("NoScavenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Log files are NOT size limited.
        /// </summary>
        internal static string NoSizeLimit {
            get {
                return ResourceManager.GetString("NoSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to purge file.
        /// </summary>
        internal static string PurgeFail {
            get {
                return ResourceManager.GetString("PurgeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Log files will be scavenged (after.
        /// </summary>
        internal static string Scavenged {
            get {
                return ResourceManager.GetString("Scavenged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem when checking for scavenging.
        /// </summary>
        internal static string ScavengeProblem {
            get {
                return ResourceManager.GetString("ScavengeProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Log files are size limited (currently.
        /// </summary>
        internal static string SizeLimited {
            get {
                return ResourceManager.GetString("SizeLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem when checking size limit.
        /// </summary>
        internal static string SizeProblem {
            get {
                return ResourceManager.GetString("SizeProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write log entry.
        /// </summary>
        internal static string WriteLogFail {
            get {
                return ResourceManager.GetString("WriteLogFail", resourceCulture);
            }
        }
    }
}
