//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrunkenBakery.OWAtray.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrunkenBakery.OWAtray.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutBox1_AboutBox1_About {
            get {
                return ResourceManager.GetString("AboutBox1_AboutBox1_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiled on .NET.
        /// </summary>
        internal static string AboutBox1_AboutBox1_Compiled_on__NET {
            get {
                return ResourceManager.GetString("AboutBox1_AboutBox1_Compiled_on__NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running on .NET v.
        /// </summary>
        internal static string AboutBox1_AboutBox1_Running_on__NET_v {
            get {
                return ResourceManager.GetString("AboutBox1_AboutBox1_Running_on__NET_v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string AboutBox1_AboutBox1_Version {
            get {
                return ResourceManager.GetString("AboutBox1_AboutBox1_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About OWA Tray Monitor.
        /// </summary>
        internal static string AboutBox1_InitializeComponent_About_OWA_Tray_Monitor {
            get {
                return ResourceManager.GetString("AboutBox1_InitializeComponent_About_OWA_Tray_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string AboutBox1_InitializeComponent_Company_Name {
            get {
                return ResourceManager.GetString("AboutBox1_InitializeComponent_Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string AboutBox1_InitializeComponent_Copyright {
            get {
                return ResourceManager.GetString("AboutBox1_InitializeComponent_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string AboutBox1_InitializeComponent_Description {
            get {
                return ResourceManager.GetString("AboutBox1_InitializeComponent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AboutBox1_InitializeComponent_OK {
            get {
                return ResourceManager.GetString("AboutBox1_InitializeComponent_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string AboutBox1_InitializeComponent_Product_Name {
            get {
                return ResourceManager.GetString("AboutBox1_InitializeComponent_Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string AboutBox1_InitializeComponent_Version {
            get {
                return ResourceManager.GetString("AboutBox1_InitializeComponent_Version", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap applications {
            get {
                object obj = ResourceManager.GetObject("applications", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap apply {
            get {
                object obj = ResourceManager.GetObject("apply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string AssemblyHelpers_ProductName_Unknown {
            get {
                return ResourceManager.GetString("AssemblyHelpers_ProductName_Unknown", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap bookmark {
            get {
                object obj = ResourceManager.GetObject("bookmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bt_play {
            get {
                object obj = ResourceManager.GetObject("bt_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log.
        /// </summary>
        internal static string ChangeLog_InitializeComponent_Change_Log {
            get {
                return ResourceManager.GetString("ChangeLog_InitializeComponent_Change_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ChangeLog_InitializeComponent_OK {
            get {
                return ResourceManager.GetString("ChangeLog_InitializeComponent_OK", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Clipboard01 {
            get {
                object obj = ResourceManager.GetObject("Clipboard01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computer {
            get {
                object obj = ResourceManager.GetObject("computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan.
        /// </summary>
        internal static string ContactUs_ContactUs_Catalan {
            get {
                return ResourceManager.GetString("ContactUs_ContactUs_Catalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string ContactUs_ContactUs_German {
            get {
                return ResourceManager.GetString("ContactUs_ContactUs_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string ContactUs_ContactUs_Spanish {
            get {
                return ResourceManager.GetString("ContactUs_ContactUs_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string ContactUs_InitializeComponent_Author {
            get {
                return ResourceManager.GetString("ContactUs_InitializeComponent_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        internal static string ContactUs_InitializeComponent_Contact_Details {
            get {
                return ResourceManager.GetString("ContactUs_InitializeComponent_Contact_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string ContactUs_InitializeComponent_Language {
            get {
                return ResourceManager.GetString("ContactUs_InitializeComponent_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ContactUs_InitializeComponent_OK {
            get {
                return ResourceManager.GetString("ContactUs_InitializeComponent_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Information.
        /// </summary>
        internal static string ContactUs_InitializeComponent_Support_Information {
            get {
                return ResourceManager.GetString("ContactUs_InitializeComponent_Support_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        internal static string ContactUs_InitializeComponent_Translations {
            get {
                return ResourceManager.GetString("ContactUs_InitializeComponent_Translations", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap email_error {
            get {
                object obj = ResourceManager.GetObject("email_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exchange {
            get {
                object obj = ResourceManager.GetObject("exchange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap font {
            get {
                object obj = ResourceManager.GetObject("font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always use IE switched.
        /// </summary>
        internal static string Form1_alwaysOpenOWAInIEToolStripMenuItem_CheckStateChanged_Always_use_IE_switched_ {
            get {
                return ResourceManager.GetString("Form1_alwaysOpenOWAInIEToolStripMenuItem_CheckStateChanged_Always_use_IE_switched" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string Form1_alwaysOpenOWAInIEToolStripMenuItem_CheckStateChanged_OFF {
            get {
                return ResourceManager.GetString("Form1_alwaysOpenOWAInIEToolStripMenuItem_CheckStateChanged_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string Form1_alwaysOpenOWAInIEToolStripMenuItem_CheckStateChanged_ON {
            get {
                return ResourceManager.GetString("Form1_alwaysOpenOWAInIEToolStripMenuItem_CheckStateChanged_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balloon notifications switched.
        /// </summary>
        internal static string Form1_balloonToolStripMenuItem_CheckStateChanged_Balloon_notifications_switched {
            get {
                return ResourceManager.GetString("Form1_balloonToolStripMenuItem_CheckStateChanged_Balloon_notifications_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balloon notifications switched .
        /// </summary>
        internal static string Form1_balloonToolStripMenuItem_CheckStateChanged_Balloon_notifications_switched_ {
            get {
                return ResourceManager.GetString("Form1_balloonToolStripMenuItem_CheckStateChanged_Balloon_notifications_switched_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EWS URL override switched.
        /// </summary>
        internal static string Form1_cbOverrideEWS_CheckedChanged_EWS_URL_override_switched {
            get {
                return ResourceManager.GetString("Form1_cbOverrideEWS_CheckedChanged_EWS_URL_override_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWA URL override switched.
        /// </summary>
        internal static string Form1_cbOverrideOWA_CheckedChanged_OWA_URL_override_switched {
            get {
                return ResourceManager.GetString("Form1_cbOverrideOWA_CheckedChanged_OWA_URL_override_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodiscovery is switched.
        /// </summary>
        internal static string Form1_chkAutodiscovery_CheckedChanged_Autodiscovery_is_switched {
            get {
                return ResourceManager.GetString("Form1_chkAutodiscovery_CheckedChanged_Autodiscovery_is_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already connected.
        /// </summary>
        internal static string Form1_ConnectToExchange_Already_connected {
            get {
                return ResourceManager.GetString("Form1_ConnectToExchange_Already_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait.
        /// </summary>
        internal static string Form1_ConnectToExchange_please_wait {
            get {
                return ResourceManager.GetString("Form1_ConnectToExchange_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transitioning state.
        /// </summary>
        internal static string Form1_ConnectToExchange_Transitioning_state {
            get {
                return ResourceManager.GetString("Form1_ConnectToExchange_Transitioning_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar notifications switched.
        /// </summary>
        internal static string Form1_disableCalendarToolStripMenuItem_CheckStateChanged_Calendar_notifications_switched {
            get {
                return ResourceManager.GetString("Form1_disableCalendarToolStripMenuItem_CheckStateChanged_Calendar_notifications_s" +
                        "witched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already disconnected.
        /// </summary>
        internal static string Form1_DisconnectFromExchange_Already_disconnected {
            get {
                return ResourceManager.GetString("Form1_DisconnectFromExchange_Already_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait.
        /// </summary>
        internal static string Form1_DisconnectFromExchange_please_wait {
            get {
                return ResourceManager.GetString("Form1_DisconnectFromExchange_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transitioning state.
        /// </summary>
        internal static string Form1_DisconnectFromExchange_Transitioning_state {
            get {
                return ResourceManager.GetString("Form1_DisconnectFromExchange_Transitioning_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminating.
        /// </summary>
        internal static string Form1_Form1_FormClosed_Terminating {
            get {
                return ResourceManager.GetString("Form1_Form1_FormClosed_Terminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Form1_Form1_Ready {
            get {
                return ResourceManager.GetString("Form1_Form1_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the.
        /// </summary>
        internal static string Form1_Form1_Welcome_to_the {
            get {
                return ResourceManager.GetString("Form1_Form1_Welcome_to_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl notifications switched.
        /// </summary>
        internal static string Form1_growlToolStripMenuItem_CheckStateChanged_Growl_notifications_switched {
            get {
                return ResourceManager.GetString("Form1_growlToolStripMenuItem_CheckStateChanged_Growl_notifications_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Details.
        /// </summary>
        internal static string Form1_InitEventView_Event_Details {
            get {
                return ResourceManager.GetString("Form1_InitEventView_Event_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Form1_InitEventView_Time {
            get {
                return ResourceManager.GetString("Form1_InitEventView_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Versions.
        /// </summary>
        internal static string Form1_InitializeComponent__NET_Versions {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent__NET_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Form1_InitializeComponent_About {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        internal static string Form1_InitializeComponent_Advanced_Settings {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Advanced_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always open OWA in IE.
        /// </summary>
        internal static string Form1_InitializeComponent_Always_open_OWA_in_IE {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Always_open_OWA_in_IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to use Autodiscovery.
        /// </summary>
        internal static string Form1_InitializeComponent_Attempt_to_use_Autodiscovery {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Attempt_to_use_Autodiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balloon.
        /// </summary>
        internal static string Form1_InitializeComponent_Balloon {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Balloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Settings.
        /// </summary>
        internal static string Form1_InitializeComponent_Basic_Settings {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Basic_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log.
        /// </summary>
        internal static string Form1_InitializeComponent_Change_Log {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Change_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string Form1_InitializeComponent_Controls {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Calendar.
        /// </summary>
        internal static string Form1_InitializeComponent_Disable_Calendar {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Disable_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address :.
        /// </summary>
        internal static string Form1_InitializeComponent_Email_Address__ {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Email_Address__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EWS URL : .
        /// </summary>
        internal static string Form1_InitializeComponent_EWS_URL___ {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_EWS_URL___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Version :.
        /// </summary>
        internal static string Form1_InitializeComponent_Exchange_Version__ {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Exchange_Version__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Form1_InitializeComponent_Exit {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string Form1_InitializeComponent_Expert {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Form1_InitializeComponent_File {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl.
        /// </summary>
        internal static string Form1_InitializeComponent_Growl {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Growl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Form1_InitializeComponent_Help {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string Form1_InitializeComponent_Logging {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Automatically.
        /// </summary>
        internal static string Form1_InitializeComponent_Login_Automatically {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Login_Automatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make OWA Default.
        /// </summary>
        internal static string Form1_InitializeComponent_Make_OWA_Default {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Make_OWA_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDAC Versions.
        /// </summary>
        internal static string Form1_InitializeComponent_MDAC_Versions {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_MDAC_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Form1_InitializeComponent_Notifications {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office365 Login Override.
        /// </summary>
        internal static string Form1_InitializeComponent_Office365_Login_Override {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Office365_Login_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Outlook.
        /// </summary>
        internal static string Form1_InitializeComponent_Open_Outlook {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Open_Outlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open OWA.
        /// </summary>
        internal static string Form1_InitializeComponent_Open_OWA {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Open_OWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Form1_InitializeComponent_Options {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Autodiscovery Validation.
        /// </summary>
        internal static string Form1_InitializeComponent_Override_Autodiscovery_Validation {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Override_Autodiscovery_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Certificate.
        /// </summary>
        internal static string Form1_InitializeComponent_Override_Certificate {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Override_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWA Tray Monitor.
        /// </summary>
        internal static string Form1_InitializeComponent_OWA_Tray_Monitor {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_OWA_Tray_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWA URL : .
        /// </summary>
        internal static string Form1_InitializeComponent_OWA_URL___ {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_OWA_URL___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string Form1_InitializeComponent_Password__ {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Password__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Sound.
        /// </summary>
        internal static string Form1_InitializeComponent_Play_Sound {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Play_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string Form1_InitializeComponent_Ready_ {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Ready_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall Last Popup.
        /// </summary>
        internal static string Form1_InitializeComponent_Recall_Last_Popup {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Recall_Last_Popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Tray Icon.
        /// </summary>
        internal static string Form1_InitializeComponent_Reset_Tray_Icon {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Reset_Tray_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at Startup.
        /// </summary>
        internal static string Form1_InitializeComponent_Run_at_Startup {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Run_at_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secs.
        /// </summary>
        internal static string Form1_InitializeComponent_secs {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_secs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address :.
        /// </summary>
        internal static string Form1_InitializeComponent_Server_Address__ {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Server_Address__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Integration.
        /// </summary>
        internal static string Form1_InitializeComponent_Shell_Integration {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Shell_Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log File.
        /// </summary>
        internal static string Form1_InitializeComponent_Show_Log_File {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Show_Log_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snarl.
        /// </summary>
        internal static string Form1_InitializeComponent_Snarl {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Snarl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Form1_InitializeComponent_Start {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Form1_InitializeComponent_Stop {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Form1_InitializeComponent_Support {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Off.
        /// </summary>
        internal static string Form1_InitializeComponent_Switch_Off {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Switch_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        internal static string Form1_InitializeComponent_System_Information {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_System_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Form1_InitializeComponent_Tools {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string Form1_InitializeComponent_unknown {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Interval :.
        /// </summary>
        internal static string Form1_InitializeComponent_Update_Interval__ {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Update_Interval__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLs.
        /// </summary>
        internal static string Form1_InitializeComponent_URLs {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_URLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default Web Proxy.
        /// </summary>
        internal static string Form1_InitializeComponent_Use_Default_Web_Proxy {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Use_Default_Web_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Domain Credentials.
        /// </summary>
        internal static string Form1_InitializeComponent_Use_Windows_Domain_Credentials {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Use_Windows_Domain_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name :.
        /// </summary>
        internal static string Form1_InitializeComponent_User_Name__ {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_User_Name__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Domain :.
        /// </summary>
        internal static string Form1_InitializeComponent_Windows_Domain__ {
            get {
                return ResourceManager.GetString("Form1_InitializeComponent_Windows_Domain__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Login is switched.
        /// </summary>
        internal static string Form1_loginAutomaticallyToolStripMenuItem_CheckStateChanged_Automatic_Login_is_switched {
            get {
                return ResourceManager.GetString("Form1_loginAutomaticallyToolStripMenuItem_CheckStateChanged_Automatic_Login_is_sw" +
                        "itched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail functions will now be handled by OWA.
        /// </summary>
        internal static string Form1_makeOWADefaultToolStripMenuItem_Click_Mail_functions_will_now_be_handled_by_OWA {
            get {
                return ResourceManager.GetString("Form1_makeOWADefaultToolStripMenuItem_Click_Mail_functions_will_now_be_handled_by" +
                        "_OWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation may fail.
        /// </summary>
        internal static string Form1_makeOWADefaultToolStripMenuItem_Click_Operation_may_fail {
            get {
                return ResourceManager.GetString("Form1_makeOWADefaultToolStripMenuItem_Click_Operation_may_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up Mail handlers.
        /// </summary>
        internal static string Form1_makeOWADefaultToolStripMenuItem_Click_Setting_up_Mail_handlers {
            get {
                return ResourceManager.GetString("Form1_makeOWADefaultToolStripMenuItem_Click_Setting_up_Mail_handlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not an Admin user.
        /// </summary>
        internal static string Form1_makeOWADefaultToolStripMenuItem_Click_You_are_not_an_Admin_user {
            get {
                return ResourceManager.GetString("Form1_makeOWADefaultToolStripMenuItem_Click_You_are_not_an_Admin_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office365 login override.
        /// </summary>
        internal static string Form1_office365LoginOverrideToolStripMenuItem_CheckStateChanged_Office365_login_override {
            get {
                return ResourceManager.GetString("Form1_office365LoginOverrideToolStripMenuItem_CheckStateChanged_Office365_login_o" +
                        "verride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodiscovery Validation override switched.
        /// </summary>
        internal static string Form1_overrideAutodiscoveryValidationToolStripMenuItem_CheckStateChanged_Autodiscovery_Validation_override_switched {
            get {
                return ResourceManager.GetString("Form1_overrideAutodiscoveryValidationToolStripMenuItem_CheckStateChanged_Autodisc" +
                        "overy_Validation_override_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL Certificate override switched.
        /// </summary>
        internal static string Form1_overrideCertificateToolStripMenuItem_CheckStateChanged_SSL_Certificate_override_switched {
            get {
                return ResourceManager.GetString("Form1_overrideCertificateToolStripMenuItem_CheckStateChanged_SSL_Certificate_over" +
                        "ride_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audible notifications switched.
        /// </summary>
        internal static string Form1_playSoundToolStripMenuItem_CheckStateChanged_Audible_notifications_switched {
            get {
                return ResourceManager.GetString("Form1_playSoundToolStripMenuItem_CheckStateChanged_Audible_notifications_switched" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subject.
        /// </summary>
        internal static string Form1_PopToast_No_Subject {
            get {
                return ResourceManager.GetString("Form1_PopToast_No_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Title.
        /// </summary>
        internal static string Form1_PopToast_No_Title {
            get {
                return ResourceManager.GetString("Form1_PopToast_No_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  not.
        /// </summary>
        internal static string Form1_RunAtStartup__not {
            get {
                return ResourceManager.GetString("Form1_RunAtStartup__not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autostart with Windows.
        /// </summary>
        internal static string Form1_RunAtStartup_autostart_with_Windows {
            get {
                return ResourceManager.GetString("Form1_RunAtStartup_autostart_with_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWAtray will.
        /// </summary>
        internal static string Form1_RunAtStartup_OWAtray_will {
            get {
                return ResourceManager.GetString("Form1_RunAtStartup_OWAtray_will", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Form1_ShellOwaUrl_Error {
            get {
                return ResourceManager.GetString("Form1_ShellOwaUrl_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snarl notifications switched.
        /// </summary>
        internal static string Form1_snarlToolStripMenuItem_CheckStateChanged_Snarl_notifications_switched {
            get {
                return ResourceManager.GetString("Form1_snarlToolStripMenuItem_CheckStateChanged_Snarl_notifications_switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation may fail.
        /// </summary>
        internal static string Form1_switchOffToolStripMenuItem_Click_Operation_may_fail {
            get {
                return ResourceManager.GetString("Form1_switchOffToolStripMenuItem_Click_Operation_may_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring Mail handlers.
        /// </summary>
        internal static string Form1_switchOffToolStripMenuItem_Click_Restoring_Mail_handlers {
            get {
                return ResourceManager.GetString("Form1_switchOffToolStripMenuItem_Click_Restoring_Mail_handlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not an Admin user.
        /// </summary>
        internal static string Form1_switchOffToolStripMenuItem_Click_You_are_not_an_Admin_user {
            get {
                return ResourceManager.GetString("Form1_switchOffToolStripMenuItem_Click_You_are_not_an_Admin_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a numeric value between 1 and .
        /// </summary>
        internal static string Form1_txtInterval_Validating_Must_be_a_numeric_value_between_1_and_ {
            get {
                return ResourceManager.GetString("Form1_txtInterval_Validating_Must_be_a_numeric_value_between_1_and_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to freshly baked at.
        /// </summary>
        internal static string Form1_WindowDressing_freshly_baked_at {
            get {
                return ResourceManager.GetString("Form1_WindowDressing_freshly_baked_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected to Exchange.
        /// </summary>
        internal static string Form1_WindowDressing_Not_Connected_to_Exchange {
            get {
                return ResourceManager.GetString("Form1_WindowDressing_Not_Connected_to_Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check log file for details.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_Check_log_file_for_details {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_Check_log_file_for_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_Connected_to {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_Connected_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to Exchange.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_Connected_to_Exchange {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_Connected_to_Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failure.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_Connection_Failure {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_Connection_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered EWS Url.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_Discovered_EWS_Url {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_Discovered_EWS_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered Mailbox Server.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_Discovered_Mailbox_Server {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_Discovered_Mailbox_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered OWA Url.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_Discovered_OWA_Url {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_Discovered_OWA_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered User Name.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_Discovered_User_Name {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_Discovered_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in your inbox.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_in_your_inbox {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_in_your_inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_minute {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_minutes {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mail from.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_New_Mail_from {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_New_Mail_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unread email.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_unread_email {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_unread_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_You_have {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_You_have", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an appointment in.
        /// </summary>
        internal static string Form1_WireUpConnectionEvents_You_have_an_appointment_in {
            get {
                return ResourceManager.GetString("Form1_WireUpConnectionEvents_You_have_an_appointment_in", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap history {
            get {
                object obj = ResourceManager.GetObject("history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightbulb {
            get {
                object obj = ResourceManager.GetObject("lightbulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail {
            get {
                object obj = ResourceManager.GetObject("mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed MDAC Versions.
        /// </summary>
        internal static string MdaCversions_InitializeComponent_Installed_MDAC_Versions {
            get {
                return ResourceManager.GetString("MdaCversions_InitializeComponent_Installed_MDAC_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDAC Inspector.
        /// </summary>
        internal static string MdaCversions_InitializeComponent_MDAC_Inspector {
            get {
                return ResourceManager.GetString("MdaCversions_InitializeComponent_MDAC_Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MdaCversions_InitializeComponent_OK {
            get {
                return ResourceManager.GetString("MdaCversions_InitializeComponent_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Version.
        /// </summary>
        internal static string MdaCversions_MdaCversions_Major_Version {
            get {
                return ResourceManager.GetString("MdaCversions_MdaCversions_Major_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        internal static string MdaCversions_MdaCversions_Revision {
            get {
                return ResourceManager.GetString("MdaCversions_MdaCversions_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Inspector.
        /// </summary>
        internal static string NeTversions_InitializeComponent__NET_Inspector {
            get {
                return ResourceManager.GetString("NeTversions_InitializeComponent__NET_Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed .NET Versions.
        /// </summary>
        internal static string NeTversions_InitializeComponent_Installed__NET_Versions {
            get {
                return ResourceManager.GetString("NeTversions_InitializeComponent_Installed__NET_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string NeTversions_InitializeComponent_OK {
            get {
                return ResourceManager.GetString("NeTversions_InitializeComponent_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Version.
        /// </summary>
        internal static string NeTversions_NeTversions_Major_Version {
            get {
                return ResourceManager.GetString("NeTversions_NeTversions_Major_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        internal static string NeTversions_NeTversions_Revision {
            get {
                return ResourceManager.GetString("NeTversions_NeTversions_Revision", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap note {
            get {
                object obj = ResourceManager.GetObject("note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap office {
            get {
                object obj = ResourceManager.GetObject("office", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap options {
            get {
                object obj = ResourceManager.GetObject("options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap outlook {
            get {
                object obj = ResourceManager.GetObject("outlook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string SysInfo_BuildTree_Computer {
            get {
                return ResourceManager.GetString("SysInfo_BuildTree_Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string SysInfo_BuildTree_Network {
            get {
                return ResourceManager.GetString("SysInfo_BuildTree_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        internal static string SysInfo_BuildTree_Operating_System {
            get {
                return ResourceManager.GetString("SysInfo_BuildTree_Operating_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string SysInfo_BuildTree_Owner {
            get {
                return ResourceManager.GetString("SysInfo_BuildTree_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string SysInfo_BuildTree_Storage {
            get {
                return ResourceManager.GetString("SysInfo_BuildTree_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bit.
        /// </summary>
        internal static string SysInfo_GetComputer_bit {
            get {
                return ResourceManager.GetString("SysInfo_GetComputer_bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        internal static string SysInfo_GetComputer_CPU {
            get {
                return ResourceManager.GetString("SysInfo_GetComputer_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string SysInfo_GetComputer_GB {
            get {
                return ResourceManager.GetString("SysInfo_GetComputer_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        internal static string SysInfo_GetComputer_Memory {
            get {
                return ResourceManager.GetString("SysInfo_GetComputer_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free.
        /// </summary>
        internal static string SysInfo_GetStorage_free {
            get {
                return ResourceManager.GetString("SysInfo_GetStorage_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string SysInfo_GetStorage_GB {
            get {
                return ResourceManager.GetString("SysInfo_GetStorage_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected System Settings.
        /// </summary>
        internal static string SysInfo_InitializeComponent_Detected_System_Settings {
            get {
                return ResourceManager.GetString("SysInfo_InitializeComponent_Detected_System_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SysInfo_InitializeComponent_OK {
            get {
                return ResourceManager.GetString("SysInfo_InitializeComponent_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        internal static string SysInfo_InitializeComponent_System_Information {
            get {
                return ResourceManager.GetString("SysInfo_InitializeComponent_System_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering data, please wait.
        /// </summary>
        internal static string SysInfo_SysInfo_Gathering_data__please_wait {
            get {
                return ResourceManager.GetString("SysInfo_SysInfo_Gathering_data__please_wait", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap toolbox {
            get {
                object obj = ResourceManager.GetObject("toolbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unlock {
            get {
                object obj = ResourceManager.GetObject("unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap web_app {
            get {
                object obj = ResourceManager.GetObject("web_app", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap win {
            get {
                object obj = ResourceManager.GetObject("win", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wizard {
            get {
                object obj = ResourceManager.GetObject("wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
