; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "OWA Tray Monitor"
!define PRODUCT_VERSION "3.0.4765.30358"
!define PRODUCT_PUBLISHER "The Drunken Bakery"
!define PRODUCT_WEB_SITE "http://www.owatray.com"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\OWAtray"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"
!include "x64.nsh"
!include "nsProcess.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "..\bin\email.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "..\bin\License.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; MUI end ------

Name "${PRODUCT_NAME}"
OutFile "OWAtray.exe"
InstallDir "$LOCALAPPDATA\OWAtray"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show
RequestExecutionLevel user

Section "MainSection" SEC01
  ${nsProcess::KillProcess} "DrunkenBakery.OWAtray.GUI.exe" $R0
  sleep 500

  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "..\bin\alert.ico"
  File "..\bin\Secure\DrunkenBakery.OWAtray.Audio.dll"
  File "..\bin\Secure\DrunkenBakery.OWAtray.Connections.Abstract.dll"
  File "..\bin\Secure\DrunkenBakery.OWAtray.Connections.EWS.dll"
  File "..\bin\Secure\DrunkenBakery.OWAtray.Connections.Proxy.dll"
  File "..\bin\Secure\DrunkenBakery.OWAtray.Framework.dll"
  File "..\bin\Secure\DrunkenBakery.OWAtray.Growl.dll"
  File "..\bin\Secure\DrunkenBakery.OWAtray.GUI.exe"
  File "..\bin\DrunkenBakery.OWAtray.GUI.exe.config"
  File "..\bin\Secure\DrunkenBakery.OWAtray.Logging.dll"
  File "..\bin\Secure\DrunkenBakery.OWAtray.ShellIntegration.exe"
  File "..\bin\DrunkenBakery.OWAtray.ShellIntegration.exe.config"
  File "..\bin\Secure\DrunkenBakery.OWAtray.Snarl.dll" 
  File "..\bin\email.ico"
  File "..\bin\email.png"
  File "..\bin\Growl.Connector.dll"
  File "..\bin\Growl.CoreLibrary.dll"
  File "..\bin\License.txt"
  File "..\bin\NLog.config"
  File "..\bin\NLog.dll"
  File "..\bin\notify.wav"
  File "..\lib\SnarlConnector.dll"

  ${If} ${RunningX64}
  File "..\bin\x64\DrunkenBakery.OWAtray.Mapi.dll"
  File /oname=Microsoft.Exchange.WebServices.dll "..\lib\Microsoft.Exchange.WebServices.x64"
  ${Else}
  File "..\bin\DrunkenBakery.OWAtray.Mapi.dll"
  File "..\lib\Microsoft.Exchange.WebServices.dll"
  ${EndIf}

  CreateDirectory "$SMPROGRAMS\OWAtray"
  CreateShortCut "$SMPROGRAMS\OWAtray\OWAtray.lnk" "$INSTDIR\DrunkenBakery.OWAtray.GUI.exe"
  CreateShortCut "$DESKTOP\OWAtray.lnk" "$INSTDIR\DrunkenBakery.OWAtray.GUI.exe"

  CreateDirectory "$INSTDIR\pl"
  SetOutPath "$INSTDIR\pl"
  File "..\bin\pl\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  File "..\bin\pl\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  File "..\bin\pl\DrunkenBakery.OWAtray.GUI.resources.dll"
  File "..\bin\pl\DrunkenBakery.OWAtray.Logging.resources.dll"
  CreateDirectory "$INSTDIR\tr"
  SetOutPath "$INSTDIR\tr"
  File "..\bin\tr\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  File "..\bin\tr\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  File "..\bin\tr\DrunkenBakery.OWAtray.GUI.resources.dll"
  File "..\bin\tr\DrunkenBakery.OWAtray.Logging.resources.dll"
  CreateDirectory "$INSTDIR\de"
  SetOutPath "$INSTDIR\de"
  File "..\bin\de\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  File "..\bin\de\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  File "..\bin\de\DrunkenBakery.OWAtray.GUI.resources.dll"
  File "..\bin\de\DrunkenBakery.OWAtray.Logging.resources.dll"
  CreateDirectory "$INSTDIR\es"
  SetOutPath "$INSTDIR\es"
  File "..\bin\es\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  File "..\bin\es\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  File "..\bin\es\DrunkenBakery.OWAtray.GUI.resources.dll"
  File "..\bin\es\DrunkenBakery.OWAtray.Logging.resources.dll"
  CreateDirectory "$INSTDIR\ca"
  SetOutPath "$INSTDIR\ca"
  File "..\bin\ca\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  File "..\bin\ca\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  File "..\bin\ca\DrunkenBakery.OWAtray.GUI.resources.dll"
  File "..\bin\ca\DrunkenBakery.OWAtray.Logging.resources.dll"
  CreateDirectory "$INSTDIR\fr"
  SetOutPath "$INSTDIR\fr"
  File "..\bin\fr\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  File "..\bin\fr\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  File "..\bin\fr\DrunkenBakery.OWAtray.GUI.resources.dll"
  File "..\bin\fr\DrunkenBakery.OWAtray.Logging.resources.dll"
  CreateDirectory "$INSTDIR\it"
  SetOutPath "$INSTDIR\it"
  File "..\bin\it\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  File "..\bin\it\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  File "..\bin\it\DrunkenBakery.OWAtray.GUI.resources.dll"
  File "..\bin\it\DrunkenBakery.OWAtray.Logging.resources.dll"
  CreateDirectory "$INSTDIR\ru"
  SetOutPath "$INSTDIR\ru"
  File "..\bin\ru\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  File "..\bin\ru\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  File "..\bin\ru\DrunkenBakery.OWAtray.GUI.resources.dll"
  File "..\bin\ru\DrunkenBakery.OWAtray.Logging.resources.dll"
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\OWAtray\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\OWAtray\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\DrunkenBakery.OWAtray.GUI.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\DrunkenBakery.OWAtray.GUI.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  ${nsProcess::KillProcess} "DrunkenBakery.OWAtray.GUI.exe" $R0
  sleep 500

  Delete "$INSTDIR\alert.ico"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.Audio.dll"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.Connections.Abstract.dll"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.Connections.EWS.dll"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.Connections.Proxy.dll"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.Framework.dll"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.Growl.dll"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.GUI.exe"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.GUI.exe.config"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.Logging.dll"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.Mapi.dll"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.ShellIntegration.exe"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.ShellIntegration.exe.config"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.Snarl.dll"
  Delete "$INSTDIR\email.ico"
  Delete "$INSTDIR\email.png"
  Delete "$INSTDIR\Growl.Connector.dll"
  Delete "$INSTDIR\Growl.CoreLibrary.dll"
  Delete "$INSTDIR\License.txt"
  Delete "$INSTDIR\NLog.config"
  Delete "$INSTDIR\Nlog.dll"
  Delete "$INSTDIR\Microsoft.Exchange.WebServices.dll"
  Delete "$INSTDIR\notify.wav"
  Delete "$INSTDIR\SnarlConnector.dll"
;
  Delete "$INSTDIR\Log4Net.config"
  Delete "$INSTDIR\log4net.dll"
;
  Delete "$INSTDIR\scenario.xml"
;
  Delete "$INSTDIR\de\DrunkenBakery.OWAtray.GUI.resources.dll"
  Delete "$INSTDIR\ca\DrunkenBakery.OWAtray.GUI.resources.dll"
  Delete "$INSTDIR\es\DrunkenBakery.OWAtray.GUI.resources.dll"
  Delete "$INSTDIR\tr\DrunkenBakery.OWAtray.GUI.resources.dll"
  Delete "$INSTDIR\fr\DrunkenBakery.OWAtray.GUI.resources.dll"
  Delete "$INSTDIR\it\DrunkenBakery.OWAtray.GUI.resources.dll"
  Delete "$INSTDIR\ru\DrunkenBakery.OWAtray.GUI.resources.dll"
  Delete "$INSTDIR\pl\DrunkenBakery.OWAtray.GUI.resources.dll"
;
  Delete "$INSTDIR\de\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  Delete "$INSTDIR\ca\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  Delete "$INSTDIR\es\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  Delete "$INSTDIR\tr\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  Delete "$INSTDIR\fr\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  Delete "$INSTDIR\it\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  Delete "$INSTDIR\ru\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
  Delete "$INSTDIR\pl\DrunkenBakery.OWAtray.Connections.Abstract.resources.dll"
;
  Delete "$INSTDIR\de\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  Delete "$INSTDIR\ca\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  Delete "$INSTDIR\es\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  Delete "$INSTDIR\tr\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  Delete "$INSTDIR\fr\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  Delete "$INSTDIR\it\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  Delete "$INSTDIR\ru\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
  Delete "$INSTDIR\pl\DrunkenBakery.OWAtray.Connections.EWS.resources.dll"
;
  Delete "$INSTDIR\de\DrunkenBakery.OWAtray.Logging.resources.dll"
  Delete "$INSTDIR\ca\DrunkenBakery.OWAtray.Logging.resources.dll"
  Delete "$INSTDIR\es\DrunkenBakery.OWAtray.Logging.resources.dll"
  Delete "$INSTDIR\tr\DrunkenBakery.OWAtray.Logging.resources.dll"
  Delete "$INSTDIR\fr\DrunkenBakery.OWAtray.Logging.resources.dll"
  Delete "$INSTDIR\it\DrunkenBakery.OWAtray.Logging.resources.dll"
  Delete "$INSTDIR\ru\DrunkenBakery.OWAtray.Logging.resources.dll"
  Delete "$INSTDIR\pl\DrunkenBakery.OWAtray.Logging.resources.dll"

  Delete "$INSTDIR\logs\*"

  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"

  Delete "$SMSTARTUP\OWA Tray Monitor.*"

  Delete "$SMPROGRAMS\OWAtray\Uninstall.lnk"
  Delete "$SMPROGRAMS\OWAtray\Website.lnk"
  Delete "$SMPROGRAMS\OWAtray\OWAtray.lnk"
  Delete "$DESKTOP\OWAtray.lnk"

  RMDir "$SMPROGRAMS\OWAtray"
  RMDir "$INSTDIR\de"
  RMDir "$INSTDIR\ca"
  RMDir "$INSTDIR\es"
  RMDir "$INSTDIR\tr"
  RMDir "$INSTDIR\fr"
  RMDir "$INSTDIR\it"
  RMDir "$INSTDIR\ru"
  RMDir "$INSTDIR\pl"
  RMDir "$INSTDIR\logs"
  RMDir "$INSTDIR"

  RMDir /r "$LOCALAPPDATA\The_Drunken_Bakery"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd