; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "OWA Tray Monitor"
!define PRODUCT_VERSION "2.0.4366.21606"
!define PRODUCT_PUBLISHER "The Drunken Bakery"
!define PRODUCT_WEB_SITE "http://www.owatray.com"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\OWAtray.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "..\email.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "..\License.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; MUI end ------

Name "${PRODUCT_NAME}"
OutFile "OWAtray.exe"
InstallDir "$LOCALAPPDATA\OWAtray"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show
RequestExecutionLevel user

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "..\bin\Release\email.png"
  File "..\bin\Release\email.ico"
  File "..\bin\Release\notify.wav"
  File "..\bin\Release\alert.ico"
  File "..\bin\Release\Growl.Connector.dll"
  File "..\bin\Release\Growl.CoreLibrary.dll"
  File "..\bin\Release\License.txt"
  File "..\bin\Release\Microsoft.Exchange.WebServices.dll"
  File "..\bin\Release\OWAtray_Secure\OWAtray.exe"
  File "..\ShellIntegration\bin\Release\DrunkenBakery.OWAtray.ShellIntegration_Secure\DrunkenBakery.OWAtray.ShellIntegration.exe"
  File "..\ShellIntegration\bin\Release\DrunkenBakery.OWAtray.ShellIntegration.exe.config"
  File "..\Mapi\Release\MapiDll.dll"
  File "..\bin\Release\OWAtray.exe.config"
  File "..\bin\Release\SnarlConnector.dll"
  File "..\bin\Release\Log4Net.config"
  File "..\bin\Release\log4net.dll"

  CreateDirectory "$SMPROGRAMS\OWAtray"
  CreateShortCut "$SMPROGRAMS\OWAtray\OWAtray.lnk" "$INSTDIR\OWAtray.exe"
  CreateShortCut "$DESKTOP\OWAtray.lnk" "$INSTDIR\OWAtray.exe"

  CreateDirectory "$INSTDIR\ca"
  SetOutPath "$INSTDIR\ca"
  File "..\bin\Release\ca\OWAtray.resources_Secure\OWAtray.resources.dll"
  CreateDirectory "$INSTDIR\de"
  SetOutPath "$INSTDIR\de"
  File "..\bin\Release\de\OWAtray.resources_Secure\OWAtray.resources.dll"
  CreateDirectory "$INSTDIR\es"
  SetOutPath "$INSTDIR\es"
  File "..\bin\Release\es\OWAtray.resources_Secure\OWAtray.resources.dll"
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\OWAtray\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\OWAtray\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\OWAtray.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\OWAtray.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\SnarlConnector.dll"
  Delete "$INSTDIR\OWAtray.exe.config"
  Delete "$INSTDIR\OWAtray.exe"
  Delete "$INSTDIR\Microsoft.Exchange.WebServices.dll"
  Delete "$INSTDIR\License.txt"
  Delete "$INSTDIR\Growl.CoreLibrary.dll"
  Delete "$INSTDIR\Growl.Connector.dll"
  Delete "$INSTDIR\email.png"
  Delete "$INSTDIR\email.ico"
  Delete "$INSTDIR\alert.ico"
  Delete "$INSTDIR\notify.wav"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.ShellIntegration.exe"
  Delete "$INSTDIR\DrunkenBakery.OWAtray.ShellIntegration.exe.config"
  Delete "$INSTDIR\MapiDll.dll"
  Delete "$INSTDIR\Log4Net.config"
  Delete "$INSTDIR\log4net.dll"
  Delete "$INSTDIR\de\OWAtray.resources.dll"
  Delete "$INSTDIR\ca\OWAtray.resources.dll"
  Delete "$INSTDIR\es\OWAtray.resources.dll"

  Delete "$SMPROGRAMS\OWAtray\Uninstall.lnk"
  Delete "$SMPROGRAMS\OWAtray\Website.lnk"
  Delete "$DESKTOP\OWAtray.lnk"
  Delete "$SMPROGRAMS\OWAtray\OWAtray.lnk"

  RMDir "$SMPROGRAMS\OWAtray"
  RMDir "$INSTDIR\de"
  RMDir "$INSTDIR\ca"
  RMDir "$INSTDIR\es"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd